// Generated by CoffeeScript 2.4.1
(function() {
  //!/usr/bin/env coffee

  // src/server.index.coffee

  var DB_Object, DB_RMI_Server;

  DB_Object = require('./lib/db_obj').DB_Object;

  DB_RMI_Server = require('./lib/db_rmi_server').DB_RMI_Server;

  exports.DB_Object = DB_Object;

  exports.DB_RMI_Server = DB_RMI_Server;

}).call(this);
