// Generated by CoffeeScript 2.4.1
(function() {
  //!/usr/bin/env coffee
  // -*- coding: utf-8 -*-

  //  db_rmi_client.coffee

  var DB_ORM, DB_RMI_Client, DB_RMI_Connection, WS_RMI_Client, WS_RMI_Connection,
    boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

  ({WS_RMI_Connection, WS_RMI_Client} = require('ws-rmi'));

  ({DB_ORM} = require('./db_orm'));

  DB_RMI_Connection = class DB_RMI_Connection extends WS_RMI_Connection {
    constructor() {
      super(...arguments);
      this.init_stubs = this.init_stubs.bind(this);
      this.init_db = this.init_db.bind(this);
    }

    init_stubs() {
      boundMethodCheck(this, DB_RMI_Connection);
      return super.init_stubs().then(this.init_db);
    }

    init_db() {
      boundMethodCheck(this, DB_RMI_Connection);
      return this.db = new DB_ORM(this.stubs.db_obj);
    }

  };

  DB_RMI_Client = class DB_RMI_Client extends WS_RMI_Client {
    constructor(options) {
      super(options, [], DB_RMI_Connection);
    }

  };

  exports.DB_RMI_Client = DB_RMI_Client;

}).call(this);
